#%RAML 0.8
title: UPnP Device
version: v1-20170401
documentation:
  - title: OCF Copyright
    content: Copyright (c) 2017 Open Connectivity Foundation, Inc. All rights reserved.
  - title: OCF License
    content: !include LICENSE.md
  - title: OCF Disclaimer
    content: !include DISCLAIMER.md
schemas:
  - upnpDevice: !include oic.r.upnp.device.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]

/upnpDeviceResURI:
  description: |
    This resource provides the specific information associated with each the UPnP Device.
    In addition, includes the link list of UPnP Service and Icon resources associated to
    the UPnP Device. It is high recommended to include the UPnP_UUID as part of the
    upnpDeviceResURI otherwise the client will need to manage the mapping to the UPnP Devices.
    /upnp/device_name/UPnP_UUID is the recommended format for upnpDeviceResURI.

  displayName: UPnP Device
  is: [ interface ]

  get:
    description: |
      Retrieves the current upnp device.
    responses:
      200:
        body:
          application/json:
            schema: upnpDevice
            example: |
              {
                "rt": ["oic.r.upnp.device", "oic.wk.col"],
                "if": ["oic.if.baseline"],
                "id": "unique_example_id",
                "deviceType": "device_type",
                "friendlyName": "friendly_name",
                "manufacturer": "manufacturer_name",
                "modelDescription": "model_description",
                "modelName": "model_name",
                "modelNumber": "model_number",
                "modelUrl": "model_url",
                "presentationUrl": "presentation_url",
                "serialNumber": "serial_number",
                "udn": "uuid:UPnP_UUID",
                "upc": "Universal_Product_Code",
                "links":
                  [
                    {
                      "href": "/icon-webResUri",
                      "mimetype": "image/png",
                      "width": 256,
                      "height": 256,
                      "media": "http://findbetter.ru/public/uploads/1481662800/2043.png",
                      "rel": "icon",
                      "rt": ["oic.r.icon"],
                      "if": ["oic.if.r"]
                    },
                    {
                      "href": "/icon-localResUri",
                      "mimetype": "image/png",
                      "width": 64,
                      "height": 64,
                      "media": "sample.png",
                      "rel": "icon",
                      "rt": ["oic.r.icon"],
                      "if": ["oic.if.r"]
                    },
                    {
                      "href": "/upnp/service-name_1st/UPnP_UUID",
                      "rt": ["oic.r.upnp.service"],
                      "if": ["oic.if.r", "oic.if.baseline"]
                    },
                    {
                      "href": "/upnp/service-name_nth/UPnP_UUID",
                      "rt": ["oic.r.upnp.service"],
                      "if": ["oic.if.r", "oic.if.baseline"]
                    }
                  ]
              }
