#%RAML 0.8
title: UPnP Device
version: v1-20170401
documentation:
        - title: OCF Copyright
          content: Copyright (c) 2017 Open Connectivity Foundation, Inc. All rights reserved.
        - title: OCF License
          content: !include LICENSE.md
        - title: OCF Disclaimer
          content: !include DISCLAIMER.md
schemas:
  - upnpDevice: !include oic.r.upnp.device.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.baseline"]

/upnpDeviceResURI:
  description: |
    This resource provides the specific information associated with each the UPnP Device.
    In addition, includes the link list of UPnP Service and Icon resources associated to the UPnP Device.

  displayName: UPnP Device
  is: [ interface ]

  get:
    description: |
      Retrieves the current upnp device.
    responses:
      200:
        body:
          application/json:
            schema: upnpDevice
            example: |
              {
                "rt": ["oic.r.upnp.device", "oic.wk.col"],
                "if": ["oic.if.baseline"],
                "ins": "uuid:UUID",
                "id": "/oic/upnp/device/uuid:UUID",
                "deviceType": "device_type",
                "friendlyName": "friendly_name",
                "manufacturer": "manufacturer_name",
                "modelDescription": "model_description",
                "modelName": "model_name",
                "modelNumber": "model_number",
                "modelURL": "model_url",
                "serialNumber": "serial_number",
                "UDN": "uuid:UUID",
                "UPC": "Universal_Product_Code",
                "links":
                  [
                    {
                      "href": "/icon-web",
                      "mimetype": "image/png",
                      "width": 256,
                      "height": 256,
                      "media": "http://findbetter.ru/public/uploads/1481662800/2043.png",
                      "rel": "icon",
                      "ins": "uuid:UUID",
                      "rt": ["oic.r.icon"],
                      "if": ["oic.if.r"]
                    },
                    {
                      "href": "/icon-local",
                      "mimetype": "image/png",
                      "width": 64,
                      "height": 64,
                      "media": "sample.png",
                      "rel": "icon",
                      "ins": "uuid:UUID",
                      "rt": ["oic.r.icon"],
                      "if": ["oic.if.r"]
                    },
                    {
                      "href": "/service-name_1st",
                      "ins": "uuid:UUID",
                      "rt": ["oic.r.upnp.service"],
                      "if": ["oic.if.baseline"]
                    },
                    {
                      "href": "/service-name_nth",
                      "ins": "uuid:UUID",
                      "rt": ["oic.r.upnp.service"],
                      "if": ["oic.if.baseline"]
                    }
                  ]
              }
