#%RAML 0.8
title: UPnP Action
version: v1-20170401
documentation:
        - title: OCF Copyright
          content: Copyright (c) 2017 Open Connectivity Foundation, Inc. All rights reserved.
        - title: OCF License
          content: !include LICENSE.md
        - title: OCF Disclaimer
          content: !include DISCLAIMER.md
schemas:
  - upnpAction: !include oic.r.upnp.action.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.rw","oic.if.baseline"]

/upnpActionResURI:
  description: |
    This resource provides the action along with inputArgs and outputArgs associated with the UPnP Service.

  displayName: UPnP Action
  is: [ interface ]

  post:
    description: |
      Changes the status of the action(s).
      Allows changes of the sourceName and the status.
    body:
      application/json:
        schema: upnpAction
        example: |
          {
          "rt": ["oic.r.upnp.action"],
          "ins": "uuid:UUID",
          "id": "/oic/upnp/service_name/uuid:UUID",
          "actionName": "action_name",
          "inputArgs": [
          {
          "genName": "arg_name_1st",
          "genType": "arg_type_1st",
          "genValue": "arg_value_1st"
          },
          {
          "genName": "arg_name_nth",
          "genType": "arg_type_nth",
          "genValue": "arg_value_nth"
          }
          ]
          }
    responses:
      200:
        body:
          application/json:
            schema: upnpAction
            example: |
              {
              "rt": ["oic.r.upnp.action"],
              "id": "unique_example_id",
              "actionName": "action_name",
              "outputArgs": [
              {
              "genName": "arg_name_1st",
              "genType": "arg_type_1st",
              "genValue": "arg_value_1st"
              },
              {
              "genName": "arg_name_nth",
              "genType": "arg_type_nth",
              "genValue": "arg_value_nth"
              }
              ]
              }
