#%RAML 0.8
title: UPnP State Variable
version: v1-20170401
documentation:
        - title: OCF Copyright
          content: Copyright (c) 2017 Open Connectivity Foundation, Inc. All rights reserved.
        - title: OCF License
          content: !include LICENSE.md
        - title: OCF Disclaimer
          content: !include DISCLAIMER.md
schemas:
  - upnpStateVariable: !include oic.r.upnp.stateVariable.json
traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.r","oic.if.baseline"]

/upnpStateVariableResURI:
  description: |
    This resource describes information associated an UPnP State Variable. It is
    high recommended to include the service_name and UPnP_UUID as part of the
    upnpStateVariableResURI otherwise the client will need to manage the mapping
    to the UPnP Devices. /upnp/service_name/UPnP_UUID/state_variable_name is the
    recommended format for upnpStateVariableResURI.

  displayName: UPnP State Variable
  is: [ interface ] # valid for all methods

  get:
    description: |
      Retrieves the current upnp state variable.
    responses:
      200:
        body:
          application/json:
            schema: upnpStateVariable
            example: |
              {
                "rt": ["oic.r.upnp.stateVariable"],
                "id": "unique_example_id",
                "name": "state_variable_name",
                "dataType": "dataType_string",
                "defaultValue": "defaultValue_string",
                "allowedValueList": [
                  {
                    "allowedValue": "allowedValue_1st"
                  },
                  {
                    "allowedValue": "allowedValue_nth"
                  }
                ]
              }
