#%RAML 0.8
title: UPnP Device Collection
version: v1-20170401
documentation:
        - title: OCF Copyright
          content: Copyright (c) 2017 Open Connectivity Foundation, Inc. All rights reserved.
        - title: OCF License
          content: !include LICENSE.md
        - title: OCF Disclaimer
          content: !include DISCLAIMER.md
schemas:
  - upnpDeviceCollection:  !include oic.r.upnp.deviceCollection.json
  - upnpDeviceCollection-ll:  !include oic.r.upnp.deviceCollection-ll.json

traits:
    - interface-baseline:
        queryParameters:
          if:
            enum: ["oic.if.baseline"]

    - interface-ll:
        queryParameters:
          if:
              enum: ["oic.if.ll"]

/upnpDeviceCollectionBaselineResURI:
  description: |
    This resource provides a collection of UPnP Devices using baseline interface (oic.if.baseline).
    The resource is a collection of instances of oic.d.light and oic.r.upnp.device detailing the individual UPnP Devices

  displayName: UPnP Device Collection - Baseline Interface
  is: [ interface-baseline ] # valid for all methods

  get:
    description: |
      Retrieves the current collection of UPnP Devices and information.
    responses:
      200:
        body:
          application/json:
            schema: upnpDeviceCollection
            example: |
              {
                "rt":    ["oic.r.upnp.deviceCollection","oic.wk.col"],
                "id":    "unique_example_id",
                "links": [
                  {"href": "/upnpLight1ResURI", "rt": ["oic.d.light"], "if": ["oic.if.r","oic.if.baseline"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]},
                  {"href": "/upnpLight2ResURI", "rt": ["oic.d.light"], "if": ["oic.if.r","oic.if.baseline"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]},
                  {"href": "/upnpDevice1ResURI", "rt": ["oic.r.upnp.device"], "if": ["oic.if.r","oic.if.baseline"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]},
                  {"href": "/upnpDevice2ResURI", "rt": ["oic.r.upnp.device"], "if": ["oic.if.r","oic.if.baseline"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]}
                ]
              }

/upnpDeviceCollectionLLResURI:
  description: |
    This resource provides a collection of UPnP Devices using link list interface (oic.if.ll).
    The resource is a collection of instances of oic.d.light and oic.r.upnp.device detailing the individual UPnP Devices

  displayName: UPnP Device Collection - Link List Interface
  is: [ interface-ll ] # valid for all methods

  get:
    responses:
      200:
        body:
          application/json:
            schema: upnpDeviceCollection-ll
            example: |
              {
                "links": [
                  {"href": "/upnpLight1ResURI", "rt": ["oic.d.light"], "if": ["oic.if.r"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]},
                  {"href": "/upnpLight2ResURI", "rt": ["oic.d.light"], "if": ["oic.if.r"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]},
                  {"href": "/upnpDevice1ResURI", "rt": ["oic.r.upnp.device"], "if": ["oic.if.r"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]},
                  {"href": "/upnpDevice2ResURI", "rt": ["oic.r.upnp.device"], "if": ["oic.if.r"], "eps": [{"ep": "coaps://[fe80::b1d6]:1122"}]}
                ]
              }
