#%RAML 0.8
title: UPnP Service
version: v1.1.0-20160519
documentation:
  - title: © 2016 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - upnpService: !include oic.r.upnp.service.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.rw","oic.if.baseline"]

/upnpServiceResURI:
  description: |
    This resource provides the list of upnp service available on the device.
    The services are an array of upnpService(s) as separately defined.
    The basic resource type oic.r.device is not able provide the actionList which are provide here in this device.

  displayName: UPnP Service
  is: [ interface ]

  get:
    description: |
      Retrieves the current upnp service.
    responses:
      200:
        body:
          application/json:
            schema: upnpService
            example: |
              {
                "rt": ["oic.r.upnp.service"],
                "id": "/oic/upnp/service/uuid:6d17120a-bfde-11d3-8c5d-97325a897ead",
                "serviceType": "urn:schemas-upnp-org:service:AVTransport:1",
                "serviceId": "urn:upnp-org:serviceId:AVTransport",
                "SCPDURL": "/aw/MediaRenderer_AVTransport/scpd.xml",
                "controlURL": "/aw/MediaRenderer_AVTransport/control",
                "eventSubURL": "/aw/MediaRenderer_AVTransport/event",
                "actionList": [
                  {
                    "actionName": "GetCurrentTransportActions",
                    "inputArgs": [
                    {
                    "genName": "InstanceID",
                    "genType": "A_ARG_TYPE_InstanceID",
                    "genValue": "arg_value_1st"
                    }
                    ]
                  },
                  {
                    "actionName": "GetDeviceCapabilities",
                    "inputArgs": [
                    {
                    "genName": "InstanceID",
                    "genType": "A_ARG_TYPE_InstanceID",
                    "genValue": "arg_value_1st"
                    }
                    ]
                  },
                  {
                    "actionName": "GetPositionInfo",
                    "inputArgs": [
                    {
                    "genName": "...etc...",
                    "genType": "...etc..",
                    "genValue": "...etc.."
                    }
                    ]
                  },
                  {
                    "actionName": "GetTransportInfo",
                    "inputArgs": [
                    {
                    "genName": "...etc...",
                    "genType": "...etc..",
                    "genValue": "...etc.."
                    }
                    ]
                  },
                  {
                    "actionName": "GetTransportSettings",
                    "inputArgs": [
                    {
                    "genName": "...etc...",
                    "genType": "...etc..",
                    "genValue": "...etc.."
                    }
                    ]
                  },
                  {
                    "actionName": "Next",
                    "inputArgs": [
                    {
                    "genName": "...etc...",
                    "genType": "...etc..",
                    "genValue": "...etc.."
                    }
                    ]
                  },
                  {
                    "actionName": "Pause",
                    "inputArgs": [
                    {
                    "genName": "...etc...",
                    "genType": "...etc..",
                    "genValue": "...etc.."
                    }
                    ]
                  },
                  {
                    "actionName": "Play",
                    "inputArgs": [
                    {
                    "genName": "...etc...",
                    "genType": "...etc..",
                    "genValue": "...etc.."
                    }
                    ]
                  },
                  {
                    "actionName": "Previous",
                    "inputArgs": [
                    {
                    "genName": "...etc...",
                    "genType": "...etc..",
                    "genValue": "...etc.."
                    }
                    ]
                  },
                  {
                    "actionName": "Seek",
                    "inputArgs": [
                    {
                    "genName": "...etc...",
                    "genType": "...etc..",
                    "genValue": "...etc.."
                    }
                    ]
                  },
                  {
                    "actionName": "SetAVTransportURI",
                    "inputArgs": [
                    {
                    "genName": "...etc...",
                    "genType": "...etc..",
                    "genValue": "...etc.."
                    }
                    ]
                  },
                  {
                    "actionName": "SetNextAVTransportURI",
                    "inputArgs": [
                    {
                    "genName": "...etc...",
                    "genType": "...etc..",
                    "genValue": "...etc.."
                    }
                    ]
                  },
                  {
                    "actionName": "SetPlayMode",
                    "inputArgs": [
                    {
                    "genName": "InstanceID",
                    "genType": "A_ARG_TYPE_InstanceID",
                    "genValue": "arg_value_1st"
                    }
                    ]
                  },
                  {
                    "actionName": "Stop",
                    "inputArgs": [
                    {
                    "genName": "InstanceID",
                    "genType": "A_ARG_TYPE_InstanceID",
                    "genValue": "arg_value_1st"
                    }
                    ]
                  }
                ],
                "serviceStateTables": [
                  {
                    "name": "CurrentPlayMode",
                    "dataType": "string",
                    "defaultValue": "NORMAL",
                    "allowedValueList": [
                      {
                        "allowedValue": "NORMAL"
                      },
                      {
                        "allowedValue": "REPEAT_ONE"
                      },
                      {
                        "allowedValue": "REPEAT_ALL"
                      },
                      {
                        "allowedValue": "RANDOM"
                      },
                      {
                        "allowedValue": "SHUFFLE"
                      }
                      ]
                    },
                    {
                      "name": "RecordStorageMedium",
                      "dataType": "string",
                      "defaultValue": "NORMAL",
                      "allowedValueList": [
                        {
                          "allowedValue": "UNKNOWN"
                        },
                        {
                          "allowedValue": "DV"
                        },
                        {
                          "allowedValue": "MINI-DV"
                        },
                        {
                          "allowedValue": "...etc..."
                        },
                        {
                          "allowedValue": "...etc..."
                        },
                        {
                          "allowedValue": "...etc..."
                        },
                        {
                          "allowedValue": "NETWORK"
                        },
                        {
                          "allowedValue": "NONE"
                        },
                        {
                          "allowedValue": "NOT_IMPLEMENTED"
                        }
                        ]
                      },
                      {
                        "name": "...etc...",
                        "dataType": "string",
                        "defaultValue": "...etc...",
                        "allowedValueList": [
                          {
                            "allowedValue": "...etc..."
                          },
                          {
                            "allowedValue": "...etc..."
                          }
                          ]
                        },
                        {
                          "name": "PossibleRecordStorageMedia",
                          "dataType": "string"
                        },
                        {
                          "name": "TransportStatus",
                          "dataType": "string",
                          "allowedValueList": [
                            {
                              "allowedValue": "OK"
                            },
                            {
                              "allowedValue": "ERROR_OCCURRED"
                            }
                            ]
                          },
                          {
                          "name": "TransportPlaySpeed",
                          "dataType": "string",
                          "defaultValue": "1",
                          "allowedValueList": [
                            {
                              "allowedValue": "1"
                            }
                          ]
                        }
                      ]
                    }
